name: CI/CD Pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '16.x'

            - name: Install dependencies
              run: npm install

            - name: Lint
              run: npm run lint

            - name: Build project
              run: npm run build

            - name: Run tests
              run: npm test

            - name: Docker login
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            - name: Build Docker image
              run: docker build -t your-docker-username/your-app-name:${{ github.sha }} .

            - name: Push Docker image
              run: docker push your-docker-username/your-app-name:${{ github.sha }}

            - name: Deploy to server
              uses: easingthemes/ssh-deploy@v2.0.7
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  ARGS: '-rltgoDzvO --delete'
                  SOURCE: 'docker-compose.yml'
                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  TARGET: '/path/to/deploy/on/remote/server'
